travis:
  secure:
    BINSTAR_TOKEN: kbunTCVk8cBy/Xy4LYTpLMYjHoOZ0KGwL4zfEU0ki3SqhF5xrR0F1UACGnJCLHe+GJc290blbXcDbJvv7IuBKFckSGkTq7ICFhoEyv2z4wubz5RAd2dczy8KlIQAV7MM27eUnwspF4Dc4o+viP8GCCzQJgU6ixxDpg9UGehCihMWqjWUKFg8zhYeLledgszlBdwEzlPW1O1PM+7d87Dld1qhKP9S45KsnWWWX++NgKqU33DzFob/Wc3zA8Nb/TsqevoxAnSlb/hURRssTPPIumjRPuKGtabDEe4KkN7zmPYtjaakFWsAA8Cjet1uLW8LSHBwEvtJGaZGbchYU8g2hfd6pqBEzBof1nLOnwSoK62Kf8ipLmP/hbpM1i2heCQLKDl/T5c2YNFoLcCCIyanixtSkgQnlVjijukAC4+0XKsn7dEE2Lj4fk+UL3v8AavJwNTOX55cMlKwmtQhbdbuhVjb1jaZmCOtfulHOJ23ct+3Wb74noC7qEmQX/wnYkrjAL8xk3Cbw53KS99D/DiTmGPaA07G8hEXuYWQsq4GvgcVdsXQdHfN7+wdSZ3v7lDuGNqg/MgvPqmARDXXQOlR2/cG4oBYnJgm1qFI4kB5MN1F5za7Go9O2o19AGYf49NMKBV06ndFvNrJwjoX1B4/rqq8RyOePc/trEyyeQUScDY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
